platform :ios, '9.0'

install! 'cocoapods',
           :deterministic_uuids => false

target 'ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'testj2objclib', :path => '../gson'
end

target 'iosTests' do
  use_frameworks!
  pod 'testj2objclib', :path => '../gson'
end